version: "3.8"
services:

  web:
    depends_on:
      - api
    ports:
      - 8000:8000
    env_file:
      - ./webapp/.env
    build: 
      context: ./webapp/
      dockerfile: Dockerfile
    volumes:
      - ./app/:/webapp/

  api:
    ports:
      - 8042:8042
    build: 
      context: ./api/
      dockerfile: Dockerfile
    