version: "3.8"
services:

  web:
    ports:
      - 8000:8000
    env_file:
      - ./webapp/.env
    build: 
      context: ./webapp/
      dockerfile: Dockerfile
    volumes:
      - ./app/:/webapp/